### ISSUE TITLE
土日開けるようにしてほしい！

### ISSUE THREAD

**Issue by oganaho** [shouhi/Hack.BAR-HP#13]
Title
------------------------------------
Hack.bar 土日も開けるようにしてほしいです！
 
詳細書く
> 7月16日(土)可能でしょうか？
お手数おかけしますが、宜しくお願いします。

Comment
------------------------------------
### 解決策
自身が考える解決策をご享受ください

> 1. 
> 2. 
> 3.

**Comment by shouhi** [comment]
7月~ 土曜日の開催を考えさせていただきます。
ただ、申し訳ございませんが7/16(土)はオープンできかねないことお詫び申し上げます。

また別日の土曜日に起こしくださること楽しみにしています。

**Comment by shouhi** [comment]
> Hack.bar 土日も開けるようにしてほしいです！

こちら8月の[リニューアルオープン](https://hackbar.jp/blog/2022/08/01/%e3%83%aa%e3%83%8b%e3%83%a5%e3%83%bc%e3%82%a2%e3%83%ab%e3%82%aa%e3%83%bc%e3%83%97%e3%83%b3/)によりオープン日を毎週金・土に変更させていただきました！

こちらのissueを参考にさせていただいたため、ご来店時に**Githubアカウントをお伝えいただけるとドリンク１杯プレゼント**いたします。ご提案本当にありがとうございました。

ご来店お待ちしています😌
