### ISSUE TITLE
「誰がスタッフか分からない」

### ISSUE THREAD

**Issue by shouhi** [shouhi/Hack.BAR-HP#4]
「誰がスタッフか分からない」と言われた
------------------------------------
 
> 服に縛りや何かがあるわけではないのでスタッフかどうかわからない

解決策
------------------------------------
### 服に名札をつける

> 1.  名札用のテンプレートを購入
> 2. 名前（あだ名等）を記入する
> 3. 出勤時に装着

**Comment by shinyamamoto0422** [comment]
名札だけでなく、どの分野に詳しいです」的なのを表示する。

**Comment by nanikasi** [comment]
難しいかもですけど、制服があったらわかりやすいかもです！
マスクの色を統一するとかでもわかりやすくなるかもです！

**Comment by shouhi** [comment]
一旦名札を作ったのでcloseします
