### ISSUE TITLE
Tech感がなさすぎるので、エンジニアが盛り上がれる(Twitterに載せてるようなネタが欲しい)

### ISSUE THREAD

**Issue by naruogram** [shouhi/Hack.BAR-HP#6]
Title
------------------------------------
タイトルだけでIssueの内容が把握できるようにする。
 
詳細書く
> 【xx画面】xxボタン押下時にエラー など...

Comment

お客さんから言われました。
------------------------------------
### 解決策
自身が考える解決策をご享受ください

> 1.  アルゴリズム問題をメニューとしておく
> 2.  メニュー表をふざける
> 3.  ライブコーディング

**Comment by shouhi** [comment]
モバイルオーダーを自作し、メニュー表をモバイルオーダーで表示するようにさせていただきました。
テック感を今後も出せるように精進していきます。！！

こちらcloseさせていただきます。
