### ISSUE TITLE
スタッフはtwitterの垢を見たら、Hack.BARで働いてるのが分かるようにする

### ISSUE THREAD

**Issue by shinyamamoto0422** [shouhi/Hack.BAR-HP#8]
# スタッフのtwitterの垢を見たら、Hack.BARで働いてるのが分かるようにする

## 概要
エンジニアはtwitterをみがちで、HACK.BARの開店時間などスタッフもそこから情報を得ると思われる。
スタッフ自身にお客さんがつく状態を目指したいので、スタッフ垢でHACK.BARで働いていることが分かるようにする。

------------------------------------
### 解決策

 1. スタッフも、Twitterの垢に @HACK.BAR的なのを名前 or プロフィール欄に記入する
### 例↓
<img width="778" alt="スクリーンショット 2022-05-24 13 38 19" src="https://user-images.githubusercontent.com/83487508/169950106-d87f0f59-c97e-4b7f-8df8-5d94f9ac3d23.png">

**Comment by shouhi** [comment]
名前のところに書いてくれるの嬉しいけど、そこまでしなくてもいいよ、、とも思う笑
名前って結構重要なポジションだからね笑

けど、プロフィールに書いてくれると嬉しいなぁ😳
